---
Name: deploynaut-dashboardmetrics
After:
  - '#deploynautroutes'
---
DNEnvironment:
  extensions:
    - 'DashboardMetrics\MenuExtension'
Director:
  rules:
    'naut/project/$Project/environment/$Environment/metrics': 'DashboardMetrics\Dispatcher',
